name: Generate Parkrun Tags

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # You can change the version based on your needs

    # Install dependencies (if you have a package.json with dependencies)
    - name: Install dependencies
      run: npm install

    # Run the JavaScript script to generate parkrun tags
    - name: Run tag generation script
      run: node .github/workflows/generate_parkrun_tags.js

    # Commit the newly generated JSON file and push it to the repository
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add parkruns_with_terrain.json
        git commit -m "Update parkruns_with_terrain.json with generated tags"
        git push
