name: Junior Web Update


on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch index.html
        run: |
          curl -o index.html https://raw.githubusercontent.com/ALD-Models/pr-tourist-map/main/index.html

      - name: Modify index.html
        run: |
          # Ensure only junior markers are visible
          sed -i 's/<input type="checkbox" id="fiveKCheckbox" checked>/<input type="checkbox" id="fiveKCheckbox" disabled>/g' index.html
          sed -i 's/<input type="checkbox" id="juniorCheckbox" checked>/<input type="checkbox" id="juniorCheckbox" checked>/g' index.html
          # Create junior.html with updated visibility
          cp index.html junior.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add junior.html
          git commit -m 'Create junior.html with only junior markers visible'
          git push

