name: Scrape Parkrun Info

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the scraper
      run: python scripts/scrape_parkrun_info.py

    - name: Commit and push the results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add parkrun_details.json
        git commit -m "Updated parkrun details"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
