name: Update Events

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch events.json from developer source
        run: |
          curl -sSL "https://images.parkrun.com/events.json" -o events.json
          jq '.' events.json > events.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add events1.json
          git commit -m "Update events.json file"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
